version: '3'

services:
  postgres:
    build: ./docker
    image: bun-elysia-database
    container_name: bun-elysia-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - bun-elysia-data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    restart: always

volumes:
  bun-elysia-data:
    driver: local
